Discord notification plugin
kestra-io/plugin-notifications pull request #74
Opened 2023-09-29 13:58 UTC by iNikitaGricenko

2023-09-29 15:32 UTC, BryceAlwaysagainst commented
I need enemity with plugin on iPhone discord please

2023-10-02 09:21 UTC, loicmathieu requested changes

2023-10-02 09:21 UTC, loicmathieu commented on src/main/java/io/kestra/plugin/notifications/discord/DiscordTemplate.java
> +        title = "Webhook username who sends"
```suggestion
        title = "Webhook username"
```

2023-10-02 09:21 UTC, loicmathieu commented on src/main/java/io/kestra/plugin/notifications/discord/DiscordTemplate.java
> +        title = "Webhook profile photo who sends"
```suggestion
        title = "Webhook profile photo URL"
```

2023-10-02 09:21 UTC, loicmathieu commented on src/main/java/io/kestra/plugin/notifications/discord/DiscordTemplate.java
> +        title = "Embed message"
```suggestion
        title = "Message description"
```

2023-10-02 09:21 UTC, loicmathieu commented on src/main/java/io/kestra/plugin/notifications/discord/DiscordTemplate.java
> +        title = "Thumbnail url"
```suggestion
        title = "Thumbnail URL"
```

2023-10-02 09:21 UTC, loicmathieu commented on src/main/java/io/kestra/plugin/notifications/discord/DiscordTemplate.java
> +        title = "Get photo from photoUrl and gets link from websiteUrl"
I don't understand the title of this property, can you reformulate?

2023-10-02 09:21 UTC, loicmathieu commented on src/main/java/io/kestra/plugin/notifications/discord/DiscordTemplate.java
> +        title = "Out of embed message"
I don't understand the title of this property, can you reformulate?

2023-10-02 09:21 UTC, loicmathieu commented on src/main/java/io/kestra/plugin/notifications/discord/DiscordTemplate.java
> +        title = "Website url"
```suggestion
        title = "Website URL"
```

2023-10-02 09:21 UTC, loicmathieu commented on src/main/java/io/kestra/plugin/notifications/discord/DiscordTemplate.java
> +        title = "Webhook profile photo who sends"
This is named avatar_url on the webhook property, please use the same property name on the task than on the Discord API to facilitate the task usage.

2023-10-02 09:21 UTC, loicmathieu commented on src/main/java/io/kestra/plugin/notifications/discord/DiscordTemplate.java
> +    @PluginProperty(dynamic = true)
```suggestion
    @PluginProperty
```
This is not rendered

2023-10-02 09:21 UTC, loicmathieu commented on src/main/java/io/kestra/plugin/notifications/discord/DiscordTemplate.java
> +    protected Color color;
Where does this `Color`class comes from? Is it from AWT?
If so, I don't think it's a good idea.
Better to allow passing color as RGB this is more standard

2023-10-02 10:10 UTC, loicmathieu approved these changes
LGTM, I made some small documentation modification that I'll apply myself on the PR.

2023-10-02 10:10 UTC, loicmathieu commented on src/main/java/io/kestra/plugin/notifications/discord/DiscordIncomingWebhook.java
> +        title = "Webhook url which should be taken from discord integrations tab"
```suggestion
        title = "Webhook URL which should be taken from discord integrations tab"
```

2023-10-02 10:10 UTC, loicmathieu commented on src/main/java/io/kestra/plugin/notifications/discord/DiscordTemplate.java
> +        title = "Webhook profile photo URL"
```suggestion
        title = "Webhook avatar URL"
```

2023-10-02 10:10 UTC, loicmathieu commented on src/main/java/io/kestra/plugin/notifications/discord/DiscordTemplate.java
> +    @PluginProperty(dynamic = true)
```suggestion
    @PluginProperty
```

2023-10-02 10:10 UTC, loicmathieu commented on src/main/java/io/kestra/plugin/notifications/discord/DiscordTemplate.java
> +        description = "Example: 255, 255, 255"
```suggestion
        description = "Example: [255, 255, 255]"
```

2023-10-02 10:15 UTC, merged