Add Sendgrid
kestra-io/plugin-notifications pull request #88
Opened 2023-10-11 14:57 UTC by iNikitaGricenko

Add sendgrid email notification plugin.
Need to figure out how to test that

2023-10-17 08:53 UTC, loicmathieu commented
@iNikitaGricenko I rebased onto master so your branch only have commits related to Sendgrid

2023-10-17 09:02 UTC, loicmathieu requested changes

2023-10-17 09:02 UTC, loicmathieu commented on src/main/java/io/kestra/plugin/notifications/sendgrid/SendGridMailSend.java
> +        mail.addContent(htmlContent);
Should be rendered

2023-10-17 09:02 UTC, loicmathieu commented on src/main/java/io/kestra/plugin/notifications/sendgrid/SendGridMailSend.java
> +            this.cc.stream().map(Email::new).forEach(personalization::addCc);
Should be rendered

2023-10-20 09:47 UTC, loicmathieu commented on src/main/java/io/kestra/plugin/notifications/sendgrid/SendGridMailSend.java
> +    )
@iNikitaGricenko I think this is the last change that you didn't tackle, can you work on it so we can proceed with the PR?

2023-10-20 09:50 UTC, loicmathieu commented
@iNikitaGricenko tests are failing can you have a look?

2023-10-26 13:21 UTC, anna-geller commented on src/main/java/io/kestra/plugin/notifications/sendgrid/SendGridMailSend.java
> +    )
@loicmathieu can you add that missing text content? then we can merge this, as Nikita fixed the failing tests ✅

2023-10-27 08:28 UTC, loicmathieu commented on src/main/java/io/kestra/plugin/notifications/sendgrid/SendGridMailSend.java
> +    )
Done

2023-10-27 08:31 UTC, loicmathieu approved these changes
LGTM, I made some small adaptation

2023-10-27 08:31 UTC, merged