Zenduty
kestra-io/plugin-notifications pull request #99
Opened 2023-10-20 10:28 UTC by iNikitaGricenko

### What changes are being made and why?

Changed body payload for zenduty integration api #94 (Removed bearer autzhorization #93)
---

2023-10-20 12:55 UTC, loicmathieu requested changes

2023-10-20 12:55 UTC, loicmathieu commented on src/main/java/io/kestra/plugin/notifications/zenduty/ZendutyTemplate.java
> +        title = "Incident title"
```suggestion
        title = "Incident message"
```

2023-10-20 12:55 UTC, loicmathieu commented on src/main/java/io/kestra/plugin/notifications/zenduty/ZendutyTemplate.java
> +        title = "Unique id for alert"
```suggestion
        title = "Unique id for the alert"
```

2023-10-20 12:55 UTC, loicmathieu commented on src/main/java/io/kestra/plugin/notifications/zenduty/ZendutyTemplate.java
> +        title = "Array urls related to alert"
```suggestion
        title = "List of URLs related to the alert"
```

This is not very descriptive, if you have more information about what those URL are please add it.

2023-10-20 12:55 UTC, loicmathieu commented on src/main/java/io/kestra/plugin/notifications/zenduty/ZendutyTemplate.java
>      @PluginProperty(dynamic = true)
```suggestion
    @PluginProperty
```

Only strings can be rendered (also remove the runContext.render above)

2023-10-20 12:55 UTC, loicmathieu commented on src/main/resources/zenduty-template.peb
> +                      {{url | json}},
```suggestion
                      {{url}},
```

I don't understand why you add the json filter here as URLs are string in the properties

2023-10-23 20:38 UTC, anna-geller commented
After rebuilding the plugin 3 times and hard-refreshing my browser 10 times, I still see alertType being set as string, not Enum. Can you validate? 
![image](https://github.com/kestra-io/plugin-notifications/assets/86264395/ebec351f-6204-44d0-823b-e9f0491645da)

2023-10-23 20:43 UTC, anna-geller commented on src/main/java/io/kestra/plugin/notifications/zenduty/ZendutyExecution.java
>                      bearerAuth: xxx000yyy111
```suggestion
```

no longer needed after adding the token

2023-10-23 20:55 UTC, anna-geller requested changes
The `ZendutyExecution` task somehow failed for me. Can you validate if you can reproduce it? You can ping me on Slack if you want to discuss or jump into a huddle 👍 thanks so much

```yaml
id: zenduty
namespace: dev

description: |
  The first issue is that alertType is still marked as a string for me without the typical autocompletion you'd get with Enum.

  Then, when using the events endpoint e.g. https://www.zenduty.com/api/events/fdbd2687-c319-4c3f-a924-fae6d83ce929/, the default payload configuration is wrong:
  Send Zenduty webhook: {"alert_type":"info","entity_id":"6mJ0bQdQNsecpVjWSoRDqG","summary":"Namespace dev, Flow ID hello_zen, Execution ID 6mJ0bQdQNsecpVjWSoRDqG, Execution Status SUCCESS. *<http://localhost:5173/ui/executions/dev/hello_zen/6mJ0bQdQNsecpVjWSoRDqG|[dev] hello_zen ➛ SUCCESS>*\n> Succeded after 00:00:02.228"}
  2023-10-23 22:41:07.820{"error": "Invalid payload"}

  When using the incident endpoint https://www.zenduty.com/api/incidents/, , the default flow from the PR body gives 500 error:

  Send Zenduty webhook: {"alert_type":"info","entity_id":"6Ag34ThLcMWEZto5ml2xF7","summary":"Namespace dev, Flow ID hello_zen, Execution ID 6Ag34ThLcMWEZto5ml2xF7, Execution Status SUCCESS. *<http://localhost:5173/ui/executions/dev/hello_zen/6Ag34ThLcMWEZto5ml2xF7|[dev] hello_zen ➛ SUCCESS>*\n> Succeded after 00:00:01.667"}
    Server Error (500)

tasks:
  - id: send_alert
    type: io.kestra.plugin.notifications.zenduty.ZendutyExecution
    url: "https://www.zenduty.com/api/incidents/" # https://www.zenduty.com/api/events/fdbd2687-c319-4c3f-a924-fae6d83ce929/
    # title: "Kestra flow failed"
    token: xxxxx
    alertType: INFO
    entityId: "{{ trigger.executionId }}"
    executionId: "{{ trigger.executionId }}"

triggers:
  - id: failed_prod_workflows
    type: io.kestra.core.models.triggers.types.Flow
    conditions:
      - type: io.kestra.core.models.conditions.types.ExecutionStatusCondition
        in:
          - SUCCESS
          - WARNING
      - type: io.kestra.core.models.conditions.types.ExecutionNamespaceCondition
        namespace: dev
        prefix: true
```

![image](https://github.com/kestra-io/plugin-notifications/assets/86264395/a2eea562-3301-419d-a452-10f55c6c82ae)

---

when using the events payload:
![image](https://github.com/kestra-io/plugin-notifications/assets/86264395/f676ebeb-ecb4-4029-9264-8ef67506ef39)

2023-10-24 09:49 UTC, iNikitaGricenko commented
I did fix body a little bit (template), change documentation to links to new (correct) api and example code in documentation. Did make test with Zenduty account:
![image](https://github.com/kestra-io/plugin-notifications/assets/82543287/20f5622f-ff7d-4600-ae1d-32cd8272a756)

2023-10-24 09:52 UTC, iNikitaGricenko commented
Seems like @anna-geller, you missed "message" field in payload when uses events payload

2023-10-24 10:37 UTC, anna-geller commented
the message is an optional attribute?

![image](https://github.com/kestra-io/plugin-notifications/assets/86264395/1a6c8c13-5dcc-4bd1-94fc-cdbff836c1d9)

and it should be optional, the goal of Execution tasks is to send default alert notifications

2023-10-24 11:26 UTC, anna-geller commented
I think this is the last part to do @iNikitaGricenko to change a default message to something like:

`message: Kestra workflow execution {{ trigger.executionId }} of a flow {{ trigger.flowId }} in the namespace {{ trigger.namespace }} changed status to {{ trigger.state }}`

atm without setting `message`, it results in an invalid payload, even though the task property is marked as optional. so we need to set a default if the user didn't provide one. after that, we can merge this and I can make some small docs adjustments afterward.

2023-10-24 11:26 UTC, iNikitaGricenko commented
> the message is an optional attribute?
> 
> ![image](https://user-images.githubusercontent.com/86264395/277631951-1a6c8c13-5dcc-4bd1-94fc-cdbff836c1d9.png)
> 
> and it should be optional, the goal of Execution tasks is to send default alert notifications

Message it is weird name of field from Zenduty. Actually it is title, so is required

2023-10-24 11:40 UTC, anna-geller approved these changes
Thanks so much!

2023-10-24 11:40 UTC, merged